### ISSUE TITLE
[PROBLEM]: add javascript beginner problem with solution (L-B)

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/javascript-problem-solving#1]
Add a javascript beginner problem with a solution. 
First, read [readme](https://github.com/devvsakib/javascript-problem-solving/blob/main/README.md) file to know how to contribute.

This issue is only for Beginner Level Problems. Anyone can work on this issue. No limit

**Comment by kennarddh** [comment]
@devvsakib Can I add NthNumberFibonacci problem?

```
NthNumberFibonacci(10) // Return 55
NthNumberFibonacci(6) // Return 8
```

**Comment by devvsakib** [comment]
@kennarddh  obviously, any problem you want.

**Comment by devvsakib** [comment]
problem 0006 added by #9

**Comment by E-fais** [comment]
Can i work on this issue..?

**Comment by devvsakib** [comment]
Of course @E-fais

**Comment by SahilSinghTomar** [comment]
can I add a new beginner level problem ?

**Comment by devvsakib** [comment]
yes @SahilSinghTomar

**Comment by SahilSinghTomar** [comment]
Can u review my PR and check if it is good or need some changes

**Comment by devvsakib** [comment]
Your PR merged already @SahilSinghTomar
