### ISSUE TITLE
[L-A]: add an Advance javascript problem

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/javascript-problem-solving#11]
Add an Advance javascript problem to L-A folder

**Comment by devvsakib** [comment]
0001 added by #10

**Comment by Akbar-Ahmed** [comment]
Hey @devvsakib Should I work on it?

**Comment by devvsakib** [comment]
sure @Akbar-Ahmed

**Comment by harisdev-netizen** [comment]
Hey @devvsakib is it still available? If yes, can I work on it?

**Comment by devvsakib** [comment]
yeah sure @harisdev-netizen

**Comment by harisdev-netizen** [comment]
Thank you @devvsakib I will start working on this. Sorry though, for getting back late to you.
