### ISSUE TITLE
[PROBLEM]: Add a javascript beginner problem with a solution. (L-I)

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/javascript-problem-solving#2]
Add a javascript beginner problem with a solution. 
First, read [readme](https://github.com/devvsakib/javascript-problem-solving/blob/main/README.md) file to know how to contribute.

This issue is only for Intermediate Level Problem

**Comment by hirentimbadiya** [comment]
i can work on this

**Comment by hirentimbadiya** [comment]
i have made a PR for this issue , kindly review it and then merge it to the main branch!!

**Comment by devvsakib** [comment]
Problem added by @hirentimbadiya , PR: #4

**Comment by kennarddh** [comment]
@devvsakib Can I create FizzBuzz problem?

**Comment by Rithik14** [comment]
Hey can i work on this issue

**Comment by devvsakib** [comment]
sure @Rithik14
