### ISSUE TITLE
add javascript problem

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/javascript-problem-solving#28]
Add some javascript problems with solution

**Comment by ibr5500** [comment]
Hello @devvsakib, can I add one?

**Comment by Sayak04** [comment]
Hi, @devvsakib can I add any problem in javascript, like Leetcode or DSA problems?

**Comment by devvsakib** [comment]
Sure thing @Sayak04

**Comment by devvsakib** [comment]
Please consider the problem level.

**Comment by 007aneesh** [comment]
Hi I want to add a problem assign to me

**Comment by devvsakib** [comment]
assigned, and please follow the guideline  @007aneesh
