### ISSUE TITLE
change link in readme file

### ISSUE THREAD

**Issue by devvsakib** [devvsakib/javascript-problem-solving#36]
Change this link to https://github.com/devvsakib/javascript-problem-solving/blob/main/README_template_for_solution.md
![image](https://user-images.githubusercontent.com/88339569/225352869-1b5aab98-2a0f-42ab-b2a0-90da36d44596.png)

**Comment by kavishshahh** [comment]
@devvsakib can you assign this to me?

**Comment by devvsakib** [comment]
Assigned @kavishshahh

**Comment by kavishshahh** [comment]
This issue is resolved. Can you close it? @devvsakib
